development:
  adapter: postgresql
  database: development_olfactory_factory
  host: localhost

production:
  adapter: postgresql
  database: production_olfactory_factory
  host: localhost

test:
  adapter: postgresql
  database: test_olfactory_factory
  host: localhost